#!/usr/bin/python
import os
try:
    from lib_lewm.main_s import main
except ImportError:
    os.sys.path.append(os.curdir)
    from lib_lewm.main_s import main

if __name__ == "__main__":
    main()
